# Generated by Django 4.1.1 on 2022-10-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeename', models.CharField(max_length=100)),
                ('Employeeaddress', models.CharField(max_length=200)),
                ('Employeenumber', models.IntegerField()),
                ('Employeeemail', models.EmailField(max_length=100)),
            ],
        ),
    ]
